/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "tp1.h"

int *
surface_1_svc(twoPar *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */
	 result = argp->p1 +argp->p2;

	return &result;
}

int *
mult_1_svc(threePar *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */
	 result = argp->p1 *argp->p2*argp->p3;

	return &result;
}
