/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "tp1.h"

bool_t
xdr_threePar (XDR *xdrs, threePar *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->p1))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->p2))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->p3))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_twoPar (XDR *xdrs, twoPar *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->p1))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->p2))
		 return FALSE;
	return TRUE;
}
