/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "tp1.h"


void
prog_1(char *host)
{
	CLIENT *clnt;
	int  *result_1;
	twoPar  surface_1_arg;
	int  *result_2;
	threePar  mult_1_arg;
	
	

#ifndef	DEBUG
	clnt = clnt_create (host, Prog, Prog_v, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
surface_1_arg.p1 = 50;
	surface_1_arg.p2 = 50;
	result_1 = surface_1(&surface_1_arg, clnt);
	
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	printf("result =%d",result_1);
	
	result_2 = mult_1(&mult_1_arg, clnt);
	if (result_2 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	printf("result =%d",result_2);
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;
	

	if (argc < 2) {
		printf ("usage: %s server_host\n", &argv[0]);
		exit (1);
	}
	host = argv[1];
	prog_1 (host);

exit (0);
}
